# Generated by Django 5.2.3 on 2025-06-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Instructor', 'Instructor')], max_length=20),
        ),
    ]
