# Generated by Django 5.2.3 on 2025-06-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='available_slot',
            field=models.IntegerField(default=20),
        ),
    ]
