# Generated by Django 5.2.3 on 2025-06-11 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_fitnessclass_available_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='client_email',
            field=models.CharField(default=datetime.datetime(2025, 6, 11, 5, 14, 5, 703685, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(default=datetime.datetime(2025, 6, 11, 5, 14, 17, 165306, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Waitlisted', 'Waitlisted')], default='confirmed', max_length=10),
        ),
    ]
